basePath: /api/v1
definitions:
  dto.BadReqErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      error:
        example: bad request from client
        type: string
    type: object
  dto.InternalErrorResponse:
    properties:
      code:
        example: 500
        type: integer
      error:
        example: internal server error
        type: string
    type: object
  dto.NotFoundErrorResponse:
    properties:
      code:
        example: 404
        type: integer
      error:
        example: task not found
        type: string
    type: object
  dto.TaskDTO:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      is_completed:
        type: boolean
      name:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Swagger for simple todo service
  termsOfService: http://swagger.io/terms/
  title: Swagger Todo API
  version: "1.0"
paths:
  /tasks:
    get:
      description: Возвращает список задач с пагинацией
      parameters:
      - default: 20
        description: Limit (pagination)
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset (pagination)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.TaskDTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.InternalErrorResponse'
      summary: Получить список задач
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Создать новую задачу
      parameters:
      - description: Тело новой задачи
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.TaskDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TaskDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.BadReqErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.InternalErrorResponse'
      summary: Создать задачу
      tags:
      - tasks
  /tasks/{id}:
    delete:
      description: Удаляет задачу по ID
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Задача удалена
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.BadReqErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.NotFoundErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.InternalErrorResponse'
      summary: Удалить задачу
      tags:
      - tasks
    get:
      description: Возвращает одну задачу по идентификатору
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TaskDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.BadReqErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.NotFoundErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.InternalErrorResponse'
      summary: Получить задачу по ID
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Обновляет задачу по ID
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      - description: Обновляемые поля
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.TaskDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TaskDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.BadReqErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.NotFoundErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.InternalErrorResponse'
      summary: Обновить задачу
      tags:
      - tasks
swagger: "2.0"
